<?php

declare(strict_types=1);

namespace VisualDesignerManager\Frontend;

use VisualDesignerManager\Navigation\NavigationRepository;

final class NavigationRenderer
{
    /** @param array<string,mixed> $props */
    public static function render(array $props, string $nodeId): string
    {
        $menuId = absint($props['menuId'] ?? 0);
        if ($menuId <= 0 || !NavigationRepository::exists($menuId)) {
            return self::placeholder();
        }

        $orientation = (string) ($props['orientation'] ?? 'horizontal');
        if (!in_array($orientation, ['horizontal', 'vertical'], true)) {
            $orientation = 'horizontal';
        }

        $align = (string) ($props['align'] ?? 'left');
        if (!in_array($align, ['left', 'center', 'right'], true)) {
            $align = 'left';
        }

        $safeNodeId = sanitize_key($nodeId);
        if ($safeNodeId === '') {
            $safeNodeId = 'navigation';
        }
        $panelId = 'vdm-navigation-panel-' . $safeNodeId;
        $toggleLabel = sanitize_text_field((string) ($props['toggleLabel'] ?? 'Menu'));
        if ($toggleLabel === '') {
            $toggleLabel = 'Menu';
        }

        $menu = wp_nav_menu([
            'menu' => $menuId,
            'container' => false,
            'menu_class' => 'vdm-navigation-menu',
            'menu_id' => '',
            'fallback_cb' => false,
            'echo' => false,
            'depth' => 0,
            'item_spacing' => 'discard',
        ]);
        if (!is_string($menu) || trim($menu) === '') {
            return self::placeholder();
        }

        ob_start();
        echo '<nav class="vdm-navigation vdm-navigation--' . esc_attr($orientation) . ' vdm-navigation--align-' . esc_attr($align) . '" aria-label="' . esc_attr($toggleLabel) . '">';
        echo '<button type="button" class="vdm-navigation-toggle" data-vdm-navigation-toggle aria-expanded="false" aria-controls="' . esc_attr($panelId) . '">';
        echo '<span class="vdm-navigation-toggle-icon" aria-hidden="true"><span></span><span></span><span></span></span>';
        echo '<span class="vdm-navigation-toggle-label">' . esc_html($toggleLabel) . '</span>';
        echo '</button>';
        echo '<div class="vdm-navigation-panel" id="' . esc_attr($panelId) . '" data-vdm-navigation-panel>';
        echo $menu; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by wp_nav_menu.
        echo '</div></nav>';

        return (string) ob_get_clean();
    }

    private static function placeholder(): string
    {
        if (is_admin() || (defined('REST_REQUEST') && REST_REQUEST)) {
            return '<div class="vdm-navigation-placeholder">Vælg en WordPress-menu i Inspector.</div>';
        }
        return '';
    }

    private function __construct()
    {
    }
}
